# Generated by Django 5.2.16 on 2026-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('type', models.CharField(default='food', max_length=50)),
                ('conditions', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('pdf', 'AI-summarized (PDF)')], default='manual', max_length=10)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='notes/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
