# Generated by Django 5.2.16 on 2026-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='verification',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('web_confirmed', 'Web-confirmed'), ('ai_corrected', 'AI-corrected'), ('ai_research', 'AI research')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pdf', 'AI-summarized (PDF)'), ('web', 'AI web research')], default='manual', max_length=10),
        ),
    ]
