# Generated by Django 5.2.16 on 2026-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_replace_conditions_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='cautions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='dosage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='other_benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='superior_benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('disease', 'Disease')], default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='other_foods',
            field=models.ManyToManyField(blank=True, related_name='other_for_diseases', to='notes.food'),
        ),
        migrations.AddField(
            model_name='note',
            name='superior_foods',
            field=models.ManyToManyField(blank=True, related_name='superior_for_diseases', to='notes.food'),
        ),
    ]
