# Generated by Django 5.2.16 on 2026-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_food_note_cautions_note_dosage_note_other_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='alternatives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='note',
            name='cautions_new',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='note',
            name='content_new',
            field=models.JSONField(default=list),
        ),
    ]
